theme: jekyll-theme-architect
title: Zhiqi Bu’s Blog
description: This is a technical blog of machine learning topics that I find interesting and insightful.
github:
  is_project_page: false
author: Zhiqi Bu
email: woodyx218@gmail.com
# Used for Sitemap.xml and your RSS feed
url: http://woodyx218.github.io 

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/tech.blog"
